### ISSUE TITLE
System limit for number of file watchers reached

### ISSUE THREAD

**Issue by Pavel-Innokentevich-Galanin** [lwwwrjke-org/po-4-wt#94]
Запускаю сервер

```
npm run start
```

Вывод в консоль такой

```
Starting the development server...

node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/public/logo192.png'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:1593:34)
    at createFsWatchInstance (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:262:21)
    at FSWatcher.<anonymous> (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:495:21)
    at FSReqCallback.oncomplete (node:fs:194:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (node:fs:194:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/public/logo192.png',
  filename: '/home/pavel-innokentevich-galanin/Documents/WT/po-4-wt/Reports/Galanin_Pavel/lab5/public/logo192.png'
}
```

Запускаем сервер

```
sudo docker-compose up start
```

Вывод в консоль такой

```
Starting lab5_start_1 ... done
Attaching to lab5_start_1
start_1    | 
start_1    | > start
start_1    | > react-scripts start
start_1    | 
start_1    | ℹ ｢wds｣: Project is running at http://172.22.0.2/
start_1    | ℹ ｢wds｣: webpack output is served from 
start_1    | ℹ ｢wds｣: Content not from webpack is served from /content/public
start_1    | ℹ ｢wds｣: 404s will fallback to /
start_1    | Starting the development server...
start_1    | 
start_1    | node:events:346
start_1    |       throw er; // Unhandled 'error' event
start_1    |       ^
start_1    | 
start_1    | Error: ENOSPC: System limit for number of file watchers reached, watch '/content/public/logo512.png'
start_1    |     at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
start_1    |     at Object.watch (node:fs:1593:34)
start_1    |     at createFsWatchInstance (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
start_1    |     at setFsWatchListener (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
start_1    |     at FSWatcher.NodeFsHandler._watchWithNodeFs (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
start_1    |     at FSWatcher.NodeFsHandler._handleFile (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:262:21)
start_1    |     at FSWatcher.<anonymous> (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:495:21)
start_1    |     at FSReqCallback.oncomplete (node:fs:194:5)
start_1    | Emitted 'error' event on FSWatcher instance at:
start_1    |     at FSWatcher._handleError (/content/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
start_1    |     at createFsWatchInstance (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
start_1    |     at setFsWatchListener (/content/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
start_1    |     [... lines matching original stack trace ...]
start_1    |     at FSReqCallback.oncomplete (node:fs:194:5) {
start_1    |   errno: -28,
start_1    |   syscall: 'watch',
start_1    |   code: 'ENOSPC',
start_1    |   path: '/content/public/logo512.png',
start_1    |   filename: '/content/public/logo512.png'
start_1    | }
start_1    | npm notice 
start_1    | npm notice New minor version of npm available! 7.7.6 -> 7.8.0
start_1    | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.8.0>
start_1    | npm notice Run `npm install -g npm@7.8.0` to update!
start_1    | npm notice 
lab5_start_1 exited with code 1
```

**Comment by Pavel-Innokentevich-Galanin** [comment]
## Решение проблемы

Помог такой вариант на [stackoverflow](https://stackoverflow.com/questions/53930305/nodemon-error-system-limit-for-number-of-file-watchers-reached).

```bash
sudo sysctl -w fs.inotify.max_user_watches=100000
```

**Теперь нет ошибок**.

## Проверка

Запускаю сервер.

```
npm run start
```

Вывод в консоль такой.

```
Compiled successfully!

You can now view undefined in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.100.15:3000

Note that the development build is not optimized.
To create a production build, use npm run build.
```

Запускаю сервер.

```
sudo docker-compose up start
```

Вывод в консоль такой.

```
Compiled successfully!

You can now view undefined in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://172.22.0.2:3000

Note that the development build is not optimized.
To create a production build, use npm run build.
```
